apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - target:
      kind: Subscription
      name: kubernetes-nmstate-operator
      namespace: openshift-nmstate
    path: patch-channel.yaml
