apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - target:
      group: mellanox.com
      kind: NicClusterPolicy
    path: patch-nic-policy.yaml
