apiVersion: v1
kind: Namespace
metadata:
  annotations:
    openshift.io/display-name: "VAST Storage Operator"
  labels:
    openshift.io/cluster-monitoring: 'true'
  name: openshift-sriov-network-operator
