kind: SriovOperatorConfig
apiVersion: sriovnetwork.openshift.io/v1
metadata:
  name: default
  namespace: openshift-nmstate
spec:
  configurationMode: daemon
  disableDrain: false
  enableInjector: true
  enableOperatorWebhook: true
  logLevel: 2